name: dart_bom
version: 1.11.0
homepage: https://github.com/ericmartineau/dart_bom.git
description: A utility for syncing dependencies across projects from a bill-of-materials pubspec
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  ansi_styles: ^0.3.2+1
  args: ^2.3.1
  cli_util: ^0.3.5
  equatable: ^2.0.5
  http: ^0.13.5
  meta: ^1.8.0
  path: ^1.8.2
  platform: ^3.1.0
  pool: ^1.5.1
  pubspec: ^2.3.0
  pub_semver: ^2.1.3
  yaml: ^3.1.1
  yaml_writer: ^1.0.3
dev_dependencies:
  lint: ^1.10.0
  test: ^1.21.0
executables: 
  syncbom: syncbom
  myversion: myversion
  lastpub: lastpub
  allpub: allpub
  repospec: repospec
  checkout: checkout
