name: dart_bom
description: A utility for syncing dependencies across projects from a bill-of-materials pubspec
version: 1.8.0
homepage: https://github.com/ericmartineau/dart_bom.git

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  syncbom: syncbom
  myversion: myversion
  lastpub: lastpub
  allpub: allpub

dependencies:
  args: ^2.3.0
  http: ^0.13.4
  path: ^1.8.0
  pubspec: ^2.1.0
  pub_semver: ^2.1.1
  
dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.1

