name: dart_bom
description: A new Flutter package project.
version: 1.2.0
homepage: https://github.com/ericmartineau/dart_bom.git

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

executables:
  dart_bom:

dependencies:
  flutter:
    sdk: flutter
  args: ^2.3.0
  path: ^1.8.0
  pubspec: ^2.1.0

dev_dependencies:
  lint: ^1.8.2
  flutter_test:
    sdk: flutter

